pg: &pg
  adapter: postgresql
  encoding: unicode
  pool: 30
  username: kurtsuki  
  password: sunshine
  host: database


development:
  <<: *pg
  database: kittens_store_dev

test:
  <<: *pg
  database: kittens_store_test

production:
  <<: *pg
  database: kittens_store